name: Build Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ZMK environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install zmk

      - name: Build firmware
        run: |
          source venv/bin/activate
          zmk build -s app -b nice_nano_v2 -- -DZMK_CONFIG=config -DSHIELD=my_5x7

      - name: Upload firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: app/build/zephyr/zmk.uf2
