name: Build Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive   # <-- สำคัญ! ต้อง clone submodules ของ ZMK

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install west
        run: |
          python -m pip install --upgrade pip
          pip install west

      - name: Initialize ZMK workspace
        run: |
          west init -l .       # กำหนด workspace เป็น repo ปัจจุบัน
          west update

      - name: Build firmware
        run: |
          west build -s app -b nice_nano_v2 -- -DZMK_CONFIG=config -DSHIELD=my_5x7

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: app/build/zephyr/zmk.uf2
